/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 nike_tn.glb 
Author: emesapril20 (https://sketchfab.com/emesapril20)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-tn-5f6401e575574b7881873fb937e96a95
Title: NIKE TN
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Nike(props) {
  const { nodes, materials } = useGLTF('/nike_tn.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[9.235, 4.575, 2.633]} rotation={[-3.072, 0, -Math.PI]} scale={109.652}>
          <mesh geometry={nodes.LORES__0.geometry} material={materials['Scene_-_Root']} position={[-0.006, 0.017, 0.003]} scale={0.138} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/nike_tn.glb')
