/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ariane_5_model.glb 
Author: bobymonsuta (https://sketchfab.com/bobymonsuta)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ariane-5-model-88a1de562245402da653bc1ae92b1b91
Title: Ariane 5 model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Rocket(props) {
  const { nodes, materials } = useGLTF('/ariane_5_model.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[90, 405, 0]}>
          <group position={[-180, 0, 0]}>
            <group position={[0, -122.656, 0]}>
              <mesh geometry={nodes.Tube_7_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, -220.844, 0]} />
              <mesh geometry={nodes.Tube_6_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, -92.094, 0]} />
              <mesh geometry={nodes.Tube_5_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, -154.594, 0]} />
              <mesh geometry={nodes.Tube_4_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, 95.406, 0]} />
              <mesh geometry={nodes.Tube_3_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, -29.594, 0]} />
              <mesh geometry={nodes.Tube_2_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, 32.906, 0]} />
              <mesh geometry={nodes.Tube_1_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, 161.906, 0]} />
              <mesh geometry={nodes.Tube_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, 206.906, 0]} />
            </group>
            <group position={[0, -0.062, 0]}>
              <group position={[0, -378.665, 0]}>
                <group position={[0, -12.993, 0]}>
                  <mesh geometry={nodes.Tube_1_2_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[0, -1.722, 0]} />
                  <mesh geometry={nodes.Tube_2_2_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[0, 1.722, 0]} />
                </group>
                <mesh geometry={nodes.Nozzle_1_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[0, -1.273, 0]} />
              </group>
              <group position={[0, -404.938, 0]}>
                <mesh geometry={nodes.Cube_1_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} rotation={[Math.PI, -1.541, Math.PI]} />
                <mesh geometry={nodes.Cube_2_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} />
              </group>
              <group position={[0, -302.915, 0]}>
                <mesh geometry={nodes.pipe_1_Pipes_white_0.geometry} material={materials.Pipes_white} rotation={[0, -0.179, -Math.PI]} />
                <mesh geometry={nodes.pipe_Pipes_white_0.geometry} material={materials.Pipes_white} rotation={[Math.PI, -1.366, 0]} />
              </group>
              <group position={[0, -135.062, 0]}>
                <mesh geometry={nodes.pipe_1_2_Pipes_white_0.geometry} material={materials.Pipes_white} rotation={[Math.PI, 1.543, -Math.PI]} />
                <mesh geometry={nodes.pipe_2_Pipes_white_0.geometry} material={materials.Pipes_white} />
              </group>
            </group>
            <mesh geometry={nodes.Cube_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[90, -405, 0]} />
            <mesh geometry={nodes.Fairing_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[0, 135, 0]} rotation={[Math.PI, 0, Math.PI]} />
            <mesh geometry={nodes.Body_2_Rocket_sec_text_0.geometry} material={materials.Rocket_sec_text} position={[0, -140.761, 0]} />
          </group>
          <group rotation={[Math.PI, 0, -Math.PI]}>
            <group position={[-90, -405, 0]}>
              <group position={[90, 282.344, 0]}>
                <mesh geometry={nodes.Tube_7_2__0.geometry} material={materials.Tube_7_2__0} position={[0, -220.844, 0]} />
                <mesh geometry={nodes.Tube_6_2__0.geometry} material={materials.Tube_7_2__0} position={[0, -92.094, 0]} />
                <mesh geometry={nodes.Tube_5_2__0.geometry} material={materials.Tube_7_2__0} position={[0, -154.594, 0]} />
                <mesh geometry={nodes.Tube_4_2__0.geometry} material={materials.Tube_7_2__0} position={[0, 95.406, 0]} />
                <mesh geometry={nodes.Tube_3_2__0.geometry} material={materials.Tube_7_2__0} position={[0, -29.594, 0]} />
                <mesh geometry={nodes.Tube_2_3__0.geometry} material={materials.Tube_7_2__0} position={[0, 32.906, 0]} />
                <mesh geometry={nodes.Tube_1_3__0.geometry} material={materials.Tube_7_2__0} position={[0, 161.906, 0]} />
                <mesh geometry={nodes.Tube_3_3__0.geometry} material={materials.Tube_7_2__0} position={[0, 206.906, 0]} />
              </group>
              <mesh geometry={nodes.Sec_rocket_text_Rocket_sec_text_1.geometry} material={materials.Rocket_sec_text} position={[90, 270, 0]} />
            </group>
            <group position={[0, -122.656, 0]}>
              <mesh geometry={nodes.Tube_7_3_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, -220.844, 0]} />
              <mesh geometry={nodes.Tube_6_3_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, -92.094, 0]} />
              <mesh geometry={nodes.Tube_5_3_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, -154.594, 0]} />
              <mesh geometry={nodes.Tube_4_3_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, 95.406, 0]} />
              <mesh geometry={nodes.Tube_3_4_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, -29.594, 0]} />
              <mesh geometry={nodes.Tube_2_4_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, 32.906, 0]} />
              <mesh geometry={nodes.Tube_1_4_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, 161.906, 0]} />
              <mesh geometry={nodes.Tube_4_4_Sec_rockets_black_0.geometry} material={materials.Sec_rockets_black} position={[0, 206.906, 0]} />
            </group>
            <group position={[0, -0.062, 0]} rotation={[Math.PI, 0, -Math.PI]}>
              <group position={[0, -404.938, 0]}>
                <mesh geometry={nodes.Cube_1_3_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} rotation={[Math.PI, -1.541, Math.PI]} />
                <mesh geometry={nodes.Cube_3_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} />
              </group>
              <group position={[0, -378.665, 0]}>
                <group position={[0, -12.993, 0]}>
                  <mesh geometry={nodes.Tube_1_5_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[0, -1.722, 0]} />
                  <mesh geometry={nodes.Tube_5_4_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[0, 1.722, 0]} />
                </group>
                <mesh geometry={nodes.Nozzle_1_2_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[0, -1.274, 0]} />
              </group>
              <group position={[0, -302.915, 0]}>
                <mesh geometry={nodes.pipe_1_3_Pipes_white_0.geometry} material={materials.Pipes_white} rotation={[0, -0.179, -Math.PI]} />
                <mesh geometry={nodes.pipe_3_Pipes_white_0.geometry} material={materials.Pipes_white} rotation={[Math.PI, -1.366, 0]} />
              </group>
              <group position={[0, -135.062, 0]}>
                <mesh geometry={nodes.pipe_4_Pipes_white_0.geometry} material={materials.Pipes_white} rotation={[Math.PI, 1.543, -Math.PI]} />
                <mesh geometry={nodes.pipe_5_Pipes_white_0.geometry} material={materials.Pipes_white} />
              </group>
            </group>
            <mesh geometry={nodes.Fairing_2_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[0, 135, 0]} rotation={[Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.Cube_1_2_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[90, -405, 0]} />
          </group>
        </group>
        <group position={[0, 443.75, 0]}>
          <group position={[43.19, -323.149, 11.128]}>
            <group position={[-10.803, -4.569, -3.203]}>
              <mesh geometry={nodes.Cylindre_2_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[-3.614, 1.439, -5.753]} rotation={[-0.021, -0.314, 1.275]} />
              <mesh geometry={nodes.Cylindre_1_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[-5.491, 1.368, 3.193]} rotation={[0.078, 0.021, 1.29]} />
              <mesh geometry={nodes.Cylindre_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[9.105, -2.807, 2.56]} rotation={[0.078, 0.021, 1.29]} />
            </group>
            <mesh geometry={nodes.Cube_2_3_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[3.917, -1.119, 1.381]} rotation={[0.273, -0.224, 0.105]} />
            <mesh geometry={nodes['Sph��re_Metal_1_0'].geometry} material={materials.Metal_1} position={[4.142, 1.776, 0.752]} />
            <mesh geometry={nodes['Sph��re_2_Metal_2_0'].geometry} material={materials.Metal_2} position={[-3.321, 1.116, -1.439]} />
          </group>
          <group position={[0, -443.75, 0]}>
            <group rotation={[Math.PI, 0, -Math.PI]}>
              <group position={[-59.456, 138.097, 27.712]}>
                <group position={[2.187, 0, -3.314]}>
                  <mesh geometry={nodes.Cylindre_2_2_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[3.799, 2.545, -0.49]} rotation={[0, 0.228, -1.442]} />
                  <mesh geometry={nodes.Cube_3_2_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[-16.073, 0, 2.968]} rotation={[0, -0.33, 0]} />
                  <mesh geometry={nodes.Cube_2_4_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[11.811, 3.586, -2.371]} rotation={[0, 0.449, 0]} />
                </group>
                <group position={[-2.187, 0, 3.314]}>
                  <mesh geometry={nodes.Cylindre_1_2_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[0.431, 1.691, 0.744]} rotation={[0, 0.064, -1.477]} />
                  <mesh geometry={nodes.Cube_1_4_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[20.477, 3.586, -1.41]} rotation={[0, 0.1, 0]} />
                  <mesh geometry={nodes.Cube_4_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[-21.044, 0, 0.675]} rotation={[0, -0.456, 0]} />
                </group>
              </group>
            </group>
            <group position={[-59.456, 138.097, 27.712]}>
              <group position={[2.187, 0, -3.314]}>
                <mesh geometry={nodes.Cylindre_3_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[3.799, 2.545, -0.49]} rotation={[0, 0.228, -1.442]} />
                <mesh geometry={nodes.Cube_3_3_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[-16.073, 0, 2.968]} rotation={[0, -0.33, 0]} />
                <mesh geometry={nodes.Cube_2_5_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[11.811, 3.586, -2.371]} rotation={[0, 0.449, 0]} />
              </group>
              <group position={[-2.187, 0, 3.314]}>
                <mesh geometry={nodes.Cylindre_1_3_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[0.431, 1.691, 0.744]} rotation={[0, 0.064, -1.477]} />
                <mesh geometry={nodes.Cube_1_5_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[20.477, 3.586, -1.41]} rotation={[0, 0.1, 0]} />
                <mesh geometry={nodes.Cube_5_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[-21.044, 0, 0.675]} rotation={[0, -0.456, 0]} />
              </group>
            </group>
          </group>
          <group position={[0, 342.141, 0]}>
            <group rotation={[Math.PI, 0, -Math.PI]}>
              <mesh geometry={nodes.Fairing_L_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} />
              <mesh geometry={nodes.Fairing_L_Metal_1_0.geometry} material={materials.Metal_1} />
              <mesh geometry={nodes.Fairing_L__0.geometry} material={materials.Tube_7_2__0} />
            </group>
            <mesh geometry={nodes.Fairing_R_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} />
            <mesh geometry={nodes.Fairing_R_Metal_1_0.geometry} material={materials.Metal_1} />
            <mesh geometry={nodes.Fairing_R__0.geometry} material={materials.Tube_7_2__0} />
          </group>
          <group position={[-0.321, -113.319, 24.863]}>
            <group position={[0.321, 234.569, -24.863]}>
              <mesh geometry={nodes.stage_sup_thruster_place_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} />
              <mesh geometry={nodes.stage_sup_thruster_place__0.geometry} material={materials.Tube_7_2__0} />
            </group>
            <group position={[-0.321, -9.569, 24.863]}>
              <group position={[8.951, 111.566, -23.959]}>
                <mesh geometry={nodes.Tuyau_4_Pipes_white_0.geometry} material={materials.Pipes_white} position={[7.947, -97.49, 25.877]} />
                <mesh geometry={nodes.Cylindre_5_Pipes_white_0.geometry} material={materials.Pipes_white} position={[-7.947, 97.49, -25.877]} rotation={[Math.PI / 2, 0, -0.298]} />
              </group>
              <group position={[-13.54, 48.831, -26.85]}>
                <mesh geometry={nodes.Cylindre_7_Pipes_white_0.geometry} material={materials.Pipes_white} position={[14.543, 76.068, -22.986]} rotation={[Math.PI / 2, 0, 0.566]} />
                <mesh geometry={nodes.Tuyau_1_Pipes_white_0.geometry} material={materials.Pipes_white} position={[-14.543, -76.068, 22.986]} />
              </group>
              <group position={[-8.039, 111.256, -24.281]}>
                <mesh geometry={nodes.Cylindre_6_Pipes_white_0.geometry} material={materials.Pipes_white} position={[9.438, 97.18, -25.411]} rotation={[Math.PI / 2, 0, 0.349]} />
                <mesh geometry={nodes.Tuyau_2_Pipes_white_0.geometry} material={materials.Pipes_white} position={[-9.438, -97.18, 25.411]} />
              </group>
              <group position={[-0.203, 50.661, 4.325]}>
                <mesh geometry={nodes.Cube_6__0.geometry} material={materials.Tube_7_2__0} position={[0.012, 75.954, -0.042]} />
                <mesh geometry={nodes.Tuyau_3_Pipes_white_0.geometry} material={materials.Pipes_white} position={[-0.012, -75.954, 0.042]} />
              </group>
              <mesh geometry={nodes.pipe_5_3_Pipes_white_0.geometry} material={materials.Pipes_white} position={[28.878, 24.378, -3.552]} />
            </group>
            <mesh geometry={nodes.Pipes_Junction_Pipes_white_0.geometry} material={materials.Pipes_white} position={[0.321, -188.865, -24.863]} />
            <mesh geometry={nodes.main_rocket_base_Rocket_main_text_0.geometry} material={materials.Rocket_main_text} position={[0.321, 9.569, -24.863]} />
          </group>
          <group position={[-14.319, -357.112, 0]}>
            <group position={[-14.289, -5.203, 0]}>
              <mesh geometry={nodes.Nozzle_pipe_1_Metal_2_0.geometry} material={materials.Metal_2} />
              <mesh geometry={nodes.Nozzle_pipe_1_Metal_1_0.geometry} material={materials.Metal_1} />
            </group>
            <group position={[14.319, 25.102, 0]}>
              <mesh geometry={nodes.Tore_5_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[0, -12.412, 0]} />
              <mesh geometry={nodes.Tore_4_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[0, -10.338, 0]} />
              <mesh geometry={nodes.Tore_3_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[0, -8.273, 0]} />
              <mesh geometry={nodes.Tore_2_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[0, 4.433, 0]} />
              <mesh geometry={nodes.Tore_1_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[0, 7.414, 0]} />
              <mesh geometry={nodes.Tore_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[0, 19.176, 0]} />
            </group>
            <group position={[23.952, -29.599, 0]}>
              <group position={[0, -0.8, 0]}>
                <group position={[-9.633, -56.238, 0]} rotation={[0, 1.396, 0]}>
                  <group position={[19.266, 58.826, 0]} rotation={[0, 0, Math.PI / 9]}>
                    <mesh geometry={nodes.Cylindre_5_3_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[0, -5.508, 0]} />
                    <mesh geometry={nodes.Cylindre_2_3_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[0, 15.399, 0]} />
                    <mesh geometry={nodes.Cylindre_5_2_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[0, 12.567, 0]} />
                    <mesh geometry={nodes.Cylindre_4_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[0, -10.953, 0]} />
                    <mesh geometry={nodes.Cylindre_2_4_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[0, -2.05, 0]} />
                    <mesh geometry={nodes.Cylindre_3_2_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[0, -0.146, 0]} />
                    <mesh geometry={nodes.Cylindre_1_4_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[0, 6.091, 0]} />
                  </group>
                </group>
                <mesh geometry={nodes.Tore_2_2_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[-9.633, -2.588, 0]} />
              </group>
              <mesh geometry={nodes.vulcain_1_Nozzle_metal_0.geometry} material={materials.Nozzle_metal} position={[-9.633, -4.367, 0]} />
            </group>
            <mesh geometry={nodes.support_pipe_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[-2.826, -6.52, 0]} rotation={[0, 0, 1.667]} />
            <mesh geometry={nodes.Nozzle_pipe_Metal_2_0.geometry} material={materials.Metal_2} position={[-33.687, 27.804, 0]} />
            <mesh geometry={nodes.rerservoir_Metal_2_0.geometry} material={materials.Metal_2} position={[-28.638, 11.805, 0]} />
            <mesh geometry={nodes.Thruster_Thruster_main_metal_0.geometry} material={materials.Thruster_main_metal} position={[14.319, 7.112, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ariane_5_model.glb')
